class PaddingContext():
    def update(self, data: bytes) -> bytes: ...
    def finalize(self) -> bytes: ...

class PKCS7(object):
    def __init__(self, block_size: int): ...
    def padder(self) -> PaddingContext: ...
    def unpadder(self) -> PaddingContext: ...
