name: setup
description: Setup dependencies
outputs:
  changed:
    description: Where dependencies have changed since the last run
    value: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
runs:
  using: composite
  steps:
  - uses: actions/setup-python@v5.0.0
    with:
      python-version: v3.12.1  # renovate github-tags:python/cpython
  - uses: actions/cache@v3.3.2
    id: cache-poetry
    with:
      path: ${{ env.pythonLocation }}
      key: poetry-${{ env.PYTHON_VERSION }}-v${{ env.POETRY_VERSION }}
    env:
      PYTHON_VERSION: v3.12.1  # renovate github-tags:python/cpython
      POETRY_VERSION: 1.7.1  # renovate pypi:poetry
  - uses: abatilo/actions-poetry@v2.4.0
    if: steps.cache-poetry.outputs.cache-hit != 'true'
    with:
      poetry-version: 1.7.1  # renovate pypi:poetry
  - uses: actions/cache@v3.3.2
    id: cache-deps
    with:
      path: ~/.cache/pypoetry
      key: deps-${{ hashFiles('poetry.lock') }}
  - run: poetry install --no-root
    if: steps.cache-deps.outputs.cache-hit != 'true'
    shell: bash
