from selenium.webdriver.remote.webdriver import WebDriver
from selenium.webdriver.remote.webelement import WebElement

class ActionChains(object):
    def __init__(self, driver: WebDriver): ...
    def move_to_element(self, to_element: WebElement) -> ActionChains: ...
    def click(self, on_element: WebElement | None = None) -> ActionChains: ...
    def perform(self) -> None: ...
