from __future__ import annotations

class WebElement:
    def find_element(self, by: str, value: str) -> WebElement: ...
    def find_elements(self, by: str, value: str) -> list[WebElement]: ...
    def click(self) -> None: ...
    def send_keys(self, *value: str) -> None: ...
    @property
    def text(self) -> str: ...
