from typing import Generic, Iterator, TypeVar

LTItemT = TypeVar("LTItemT", bound=LTItem)

class LTComponent(LTItem): ...
class LTExpandableContainer(LTContainer[LTItemT]): ...
class LTItem: ...
class LTLayoutContainer(LTContainer[LTComponent]): ...
class LTPage(LTLayoutContainer): ...
class LTText: ...

class LTContainer(LTComponent, Generic[LTItemT]):
    def __iter__(self) -> Iterator[LTItemT]: ...

class LTTextContainer(LTExpandableContainer[LTItemT], LTText):
    def get_text(self) -> str: ...

class LAParams:
    def __init__(self, line_margin: float): ...
