name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: v3.10.0  # renovate github-tags:python/cpython
    - name: Setup Poetry
      uses: abatilo/actions-poetry@v2.1.4
      with:
        poetry-version: 1.1.11  # renovate pypi:poetry
    - name: Setup Dependencies
      run: poetry install
    - name: Lint
      run: poetry run flake8
