name: vulnerabilities
on:
  schedule:
  - cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.0
    - name: Setup
      uses: ./.github/actions/setup
    - name: Scan Dependencies for Vulnerabilities
      uses: ./.github/actions/vulnerabilities
